/* =====================================================================================
   TEXTES OFFICIELS À REPRODUIRE INTÉGRALEMENT (à peine de nullité) — copiés de Légifrance
   le 2 octobre 2026. La veille mensuelle vérifie que ces versions sont toujours en vigueur.
   ===================================================================================== */
const TEXTES_OFFICIELS = {
  art17_2_I: { titre:'Article 17-2, I, de la loi n° 89-462 du 6 juillet 1989', version:'en vigueur depuis le 24 août 2022 (loi n° 2021-1104 du 22 août 2021, art. 159)',
    src:'https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000043977083', alineas:[
    'I. - Lors du renouvellement du contrat, le loyer ne donne lieu à réévaluation que s\'il est manifestement sous-évalué.',
    'Dans ce cas, le bailleur peut proposer au locataire, au moins six mois avant le terme du contrat et dans les conditions de forme prévues à l\'article 15, un nouveau loyer fixé par référence aux loyers habituellement constatés dans le voisinage pour des logements comparables.',
    'Les loyers servant de références doivent être représentatifs de l\'ensemble des loyers habituellement constatés dans le voisinage pour des logements comparables, situés soit dans le même groupe d\'immeubles, soit dans tout autre groupe d\'immeubles comportant des caractéristiques similaires et situés dans la même zone géographique. Un décret en Conseil d\'Etat définit les éléments constitutifs de ces références.',
    'Le nombre minimal de références à fournir est de trois. Toutefois, il est de six dans les communes, dont la liste est fixée par décret, faisant partie d\'une agglomération de plus d\'un million d\'habitants.',
    'Lorsque le bailleur fait application des dispositions du présent I, il ne peut donner congé au locataire pour la même échéance du contrat.',
    'La notification reproduit intégralement, à peine de nullité, les dispositions du présent I et mentionne le montant du loyer ainsi que la liste des références ayant servi à le déterminer.',
    'En cas de désaccord ou à défaut de réponse du locataire quatre mois avant le terme du contrat, l\'une ou l\'autre des parties saisit la commission départementale de conciliation.',
    'A défaut d\'accord constaté par la commission, le juge est saisi avant le terme du contrat. A défaut de saisine, le contrat est reconduit de plein droit aux conditions antérieures du loyer, éventuellement révisé. Le contrat dont le loyer est fixé judiciairement est réputé renouvelé pour la durée définie à l\'article 10 à compter de la date d\'expiration du contrat. La décision du juge est exécutoire par provision.',
    'La hausse convenue entre les parties ou fixée judiciairement s\'applique par tiers ou par sixième selon la durée du contrat.',
    'Toutefois, cette hausse s\'applique par sixième annuel au contrat renouvelé, puis lors du renouvellement ultérieur, dès lors qu\'elle est supérieure à 10 % si le premier renouvellement avait une durée inférieure à six ans.',
    'La révision éventuelle résultant de l\'article 17-1 s\'applique à chaque valeur ainsi définie.' ] },
  art15_II_5: { titre:'Article 15, II, cinq premiers alinéas, de la loi n° 89-462 du 6 juillet 1989', version:'en vigueur depuis le 29 juillet 2023 (loi n° 2023-668 du 27 juillet 2023)',
    src:'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000509310', alineas:[
    'II. - Lorsqu\'il est fondé sur la décision de vendre le logement, le congé doit, à peine de nullité, indiquer le prix et les conditions de la vente projetée. Le congé vaut offre de vente au profit du locataire : l\'offre est valable pendant les deux premiers mois du délai de préavis. Les dispositions de l\'article 46 de la loi n° 65-557 du 10 juillet 1965 fixant le statut de la copropriété des immeubles bâtis ne sont pas applicables au congé fondé sur la décision de vendre le logement.',
    'A l\'expiration du délai de préavis, le locataire qui n\'a pas accepté l\'offre de vente est déchu de plein droit de tout titre d\'occupation sur le local.',
    'Le locataire qui accepte l\'offre dispose, à compter de la date d\'envoi de sa réponse au bailleur, d\'un délai de deux mois pour la réalisation de l\'acte de vente. Si, dans sa réponse, il notifie son intention de recourir à un prêt, l\'acceptation par le locataire de l\'offre de vente est subordonnée à l\'obtention du prêt et le délai de réalisation de la vente est porté à quatre mois. Le contrat de location est prorogé jusqu\'à l\'expiration du délai de réalisation de la vente. Si, à l\'expiration de ce délai, la vente n\'a pas été réalisée, l\'acceptation de l\'offre de vente est nulle de plein droit et le locataire est déchu de plein droit de tout titre d\'occupation.',
    'Dans le cas où le propriétaire décide de vendre à des conditions ou à un prix plus avantageux pour l\'acquéreur, le notaire doit, lorsque le bailleur n\'y a pas préalablement procédé, notifier au locataire ces conditions et prix à peine de nullité de la vente. Cette notification est effectuée à l\'adresse indiquée à cet effet par le locataire au bailleur ; si le locataire n\'a pas fait connaître cette adresse au bailleur, la notification est effectuée à l\'adresse des locaux dont la location avait été consentie. Elle vaut offre de vente au profit du locataire. Cette offre est valable pendant une durée d\'un mois à compter de sa réception. L\'offre qui n\'a pas été acceptée dans le délai d\'un mois est caduque.',
    'Le locataire qui accepte l\'offre ainsi notifiée dispose, à compter de la date d\'envoi de sa réponse au bailleur ou au notaire, d\'un délai de deux mois pour la réalisation de l\'acte de vente. Si, dans sa réponse, il notifie son intention de recourir à un prêt, l\'acceptation par le locataire de l\'offre de vente est subordonnée à l\'obtention du prêt et le délai de réalisation de la vente est porté à quatre mois. Si, à l\'expiration de ce délai, la vente n\'a pas été réalisée, l\'acceptation de l\'offre de vente est nulle de plein droit.' ] }
};
function texteOfficielHtml(k){ const t=TEXTES_OFFICIELS[k]; return `<div class="texteoff"><h3>Annexe — ${esc(t.titre)}</h3><p class="small">Texte reproduit intégralement (version ${esc(t.version)}).</p>${t.alineas.map(a=>'<p>'+esc(a)+'</p>').join('')}</div>`; }
